### ISSUE TITLE
Search for public bodies does not work on dev installation

### ISSUE THREAD

**Issue by rixx** [okfde/froide#243]
I followed the development guide and tried to add a request in the frontend after adding a public body, FOI law, and category via the Django admin. Going to the dev page at http://localhost:8000/make-request/#step-publicbody led to this traceback:

```
Internal Server Error: /api/v1/publicbody/search/
Traceback (most recent call last):
  File "/home/rixx/.virtualenvs/froide/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/rixx/.virtualenvs/froide/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/rixx/.virtualenvs/froide/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rixx/.virtualenvs/froide/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rixx/.virtualenvs/froide/lib/python3.6/site-packages/rest_framework/viewsets.py", line 95, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/rixx/.virtualenvs/froide/lib/python3.6/site-packages/rest_framework/views.py", line 494, in dispatch
    response = self.handle_exception(exc)
  File "/home/rixx/.virtualenvs/froide/lib/python3.6/site-packages/rest_framework/views.py", line 454, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/rixx/.virtualenvs/froide/lib/python3.6/site-packages/rest_framework/views.py", line 491, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/rixx/Projects/external/froide/froide/publicbody/api_views.py", line 309, in search
    data = serializer.data
  File "/home/rixx/Projects/external/froide/froide/helper/api_utils.py", line 28, in data
    ret = super(ListSerializer, self).data
  File "/home/rixx/.virtualenvs/froide/lib/python3.6/site-packages/rest_framework/serializers.py", line 262, in data
    self._data = self.to_representation(self.instance)
  File "/home/rixx/Projects/external/froide/froide/helper/api_utils.py", line 32, in to_representation
    ret = super(SearchFacetListSerializer, self).to_representation(instance)
  File "/home/rixx/.virtualenvs/froide/lib/python3.6/site-packages/rest_framework/serializers.py", line 660, in to_representation
    self.child.to_representation(item) for item in iterable
  File "/home/rixx/.virtualenvs/froide/lib/python3.6/site-packages/rest_framework/serializers.py", line 660, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/home/rixx/.virtualenvs/froide/lib/python3.6/site-packages/rest_framework/serializers.py", line 504, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/home/rixx/.virtualenvs/froide/lib/python3.6/site-packages/rest_framework/serializers.py", line 491, in to_representation
    attribute = field.get_attribute(instance)
  File "/home/rixx/.virtualenvs/froide/lib/python3.6/site-packages/rest_framework/fields.py", line 441, in get_attribute
    return get_attribute(instance, self.source_attrs)
  File "/home/rixx/.virtualenvs/froide/lib/python3.6/site-packages/rest_framework/fields.py", line 105, in get_attribute
    instance = instance()
  File "/home/rixx/Projects/external/froide/froide/publicbody/models.py", line 67, in get_absolute_domain_url
    return "%s%s" % (settings.SITE_URL, self.get_absolute_url())
  File "/home/rixx/Projects/external/froide/froide/publicbody/models.py", line 64, in get_absolute_url
    kwargs={'slug': self.slug})
  File "/home/rixx/.virtualenvs/froide/lib/python3.6/site-packages/django/urls/base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/home/rixx/.virtualenvs/froide/lib/python3.6/site-packages/django/urls/resolvers.py", line 497, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'publicbody-show_jurisdiction' with keyword arguments '{'slug': ''}' not found. 1 pattern(s) tried: ['jurisdiction/(?P<slug>[\\w-]+)/$']
```

**Comment by stefanw** [comment]
This looks like there's a jurisdiction with a blank slug. This could have many causes, but possibly just fix the jurisdiction's slug to be non-empty?

**Comment by rixx** [comment]
(I think creting a jurisdiction with an empty slug should not work, but I agree that it's a setup error, so closing.)
