### ISSUE TITLE
Ical random connection errors

### ISSUE THREAD

**Issue by rugk** [okfde/froide#423]
## STR

1. Go to https://fragdenstaat.de/account/subscriptions/ and copy your ical URL.
2. Import that into your Android calender with [ICSx⁵](https://icsx5.bitfire.at/) v1.9.1.

## What happens

I regularly get connection errors:
```
Failed to connect to fragdenstaat.de/94.130.55.89:443

java.net.ConnectException: Failed to connect to fragdenstaat.de/94.130.55.89:443
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:297)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at at.bitfire.icsdroid.CalendarFetcher.fetchNetwork(CalendarFetcher.kt:129)
	at at.bitfire.icsdroid.CalendarFetcher.run(CalendarFetcher.kt:44)
	at at.bitfire.icsdroid.ProcessEventsTask.processEvents(ProcessEventsTask.kt:101)
	at at.bitfire.icsdroid.ProcessEventsTask.run(ProcessEventsTask.kt:34)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.net.ConnectException: failed to connect to fragdenstaat.de/94.130.55.89 (port 443) from /192.168.1.100 (port 39794) after 10000ms: isConnected failed: ECONNABORTED (Software caused connection abort)
	at libcore.io.IoBridge.isConnected(IoBridge.java:288)
	at libcore.io.IoBridge.connectErrno(IoBridge.java:193)
	at libcore.io.IoBridge.connect(IoBridge.java:135)
	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
	at java.net.Socket.connect(Socket.java:621)
	at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:120)
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
	... 22 more
Caused by: android.system.ErrnoException: isConnected failed: ECONNABORTED (Software caused connection abort)
	at libcore.io.IoBridge.isConnected(IoBridge.java:275)
	... 32 more
```

![ical-fragdenstaat](https://user-images.githubusercontent.com/11966684/109475560-29be5080-7a76-11eb-8d3e-38513b492a86.png)

## What should happen

No error.
I have not seen this yet for any other calendar/Android service, but of course I cannot guarantee it's not a random connection issue at my side.

Accessing the FragDenStaat.de website always works fine, I've never seen an error.

## System

Android 10
It may be it has no IPv6 connectivity, but it seems to use IPv4 as we can see, so I guess that's no problem.

**Comment by stefanw** [comment]
Could it be that this Java version cannot deal with modern HTTPS?
The [SSL Labs analysis](https://www.ssllabs.com/ssltest/analyze.html?d=fragdenstaat.de&s=94.130.55.89&latest) shows incompatibility with older Android/Java versions due to missing SNI or unsupported ciphers.

**Comment by rugk** [comment]
It's Android 10… :shrug: 

Also it only happens randomly, ~~sometimes~~ usually(?) it works and I can properly see the entries in my calendar.
